services:
  authserver:
    build:
      context: authserver
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - authserver
