services:
  authserver:
    build:
      context: authserver
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - path: /api/.env
        required: false
    environment:
      OAUTH_HOST: authserver
    depends_on:
      - authserver

  api-test:
    image: gradle:8.10-jdk17
    working_dir: /api
    volumes:
      - .:/api
    command: ./gradlew test --no-daemon --rerun-tasks
    profiles:
      - test
