server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://${OAUTH_HOST:localhost}:${OAUTH_PORT:8081}${OAUTH_INTROSPECTION_ENDPOINT:/token/introspect}
          client-id: ${OAUTH_CLIENT_ID:client1}
          client-secret: ${OAUTH_CLIENT_SECRET:abcde12345}