server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${OAUTH_INTROSPECTION_URI:http://localhost:8081/token/introspect}
          client-id: ${OAUTH_CLIENT_ID:client1}
          client-secret: ${OAUTH_CLIENT_SECRET:abcde12345}