plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.raidiam'
version = '0.0.1-SNAPSHOT'
description = 'Tech Task for Raidiam Conformance'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.apache.commons:commons-lang3:3.20.0'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'


	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


	compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.test {
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "short"

        afterSuite { desc, result ->
            if (!desc.parent) {
                println ""
                println "🧪 Test Summary (API)"
                println "----------------------------"
                println "✅ Passed:  ${result.successfulTestCount}"
                println "❌ Failed:  ${result.failedTestCount}"
                println "⚠️ Skipped: ${result.skippedTestCount}"
                println "⏱ Total:   ${result.testCount}"
            }
        }
    }
}
